version: '3.8'

services:
  user_ms:
    build: .
    network_mode: host
    container_name: user_ms
    restart: always
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
